### ISSUE TITLE
url: 'file//index.html'

### ISSUE THREAD

**Issue by patricksebastien** [eliquious/electronify-server#14]
Hi,
I need to use the http:// protocol so that Google Tag Manager works in my application (right now I am using the standard way: mainWindow.loadURL('file://' + __dirname + '/index.html')).

Would it be possible to load my local index.html file ie:
```
electronify({
  url: 'file://index.html',
```
Is there any impact at all in my application by using your solution?

Thanks

**Comment by eliquious** [comment]
@patricksebastien `window.loadURL` is also used in `electronify-server` to load the page. So you shouldn't have any issues as long as the `file://` location is correct.
