### ISSUE TITLE
Where to put web app files?

### ISSUE THREAD

**Issue by facetime88** [eliquious/electronify-server#15]
Hi, I am sorry if this sounds to be silly. I am new with electron.
I have built a web app pure in html and jquery. I'd like to run this web app locally, means, in the main js file, I put some config like below:

`mainWindow.loadURL(url.format({
		pathname: path.join(__dirname, 'html/index.html'),
		protocol: 'file:',
		slashes: true
	}));`

The web app itself will load some additional local files using $.get command. And as we know, it will failed because of the Cross Origin issue. So it seems the only solution is to host it on a server.

Then I found electronify-server, but don't understand yet where to place the html files. Let say the electronify-server config is set to load from 127.0.0.1:80. My question is where is the 127.0.0.1:80 physical location? How do I set the location?

Thank you.

**Comment by eliquious** [comment]
@facetime88 there are several solutions, but the simplest is to use a tiny node server to serve the files. If you look at the `static` example you'll see how to do it. You may also be able to update your code to use relative paths to each of the resources.

The `static` example has the resources in the `dist/` folder which is fairly standard. Then the `main.js` uses `server.js` to serve the files.
