### ISSUE TITLE
Close the server?

### ISSUE THREAD

**Issue by Themercee** [eliquious/electronify-server#3]
I try to find how to close the server, but could not find one. I am on Windows and I need to close it manually. Would be a nice :P

**Comment by eliquious** [comment]
@Themercee I can add a way to kill the child process. How do you plan to use the feature? It may help me decide the best way to implement it.

**Comment by eliquious** [comment]
@Themercee You can kill the server by sending it a signal.

```
var childProcess = undefined;
electronify({
  command: '[COMMAND]',
  url: 'http://127.0.0.1:[PORT]',
}).on('child-started', function(child) {
  childProcess = child;

  // setup logging on child process
  child.stdout.on('data', log);
  child.stderr.on('data', log);
}).on('child-error', function(err, app) {
  // handle a server crash
});


// You can then kill the server later like this:
childProcess.kill('SIGINT');

```

The trick is to save the child process for later use. You have access to it via the `child-started` event. Whenever you need to kill it just call `childProcess.kill('SIGINT');`.

**Comment by Themercee** [comment]
Nice thanks for the answer! Sorry for late reply, my github account wasn't set for notification, I correct this. :+1:
