### ISSUE TITLE
Clear the cache ?

### ISSUE THREAD

**Issue by ozee31** [eliquious/electronify-server#6]
Hi,

This package is good, but when change an asset and i run the server, I see no change.

The last version is in cache. How clear the cache ?

Thk

**Comment by eliquious** [comment]
I haven't tried this but it looks like there are a couple ways to do it. You can do it through the dev console manually or it looks like you can do it through the Electron API.

_[Session.clearCache](https://github.com/electron/electron/blob/master/docs/api/session.md#sesclearcachecallback)_

```
const {session} = require('electron');
session.defaultSession.clearCache(func(){
  // Cache has been cleared.
});
```

That might work.

**Comment by ozee31** [comment]
Ok it's good.

Just add `session.defaultSession.clearCache(function(){});` in ready function
